In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
all_data = pd.read_csv("https://bit.ly/3BVJ2ip")

In [8]:
all_data

,RED,GREEN,BLUE,LIGHT_OR_DARK_FONT_IND
0,0,0,0,1
1,0,0,128,1
2,0,0,139,1
3,0,0,205,1
4,0,0,238,1
...,...,...,...,...
1340,95,158,160,0
1341,96,123,139,1
1342,97,97,97,1
1343,99,184,255,0


In [16]:
all_data.iloc[:,0:3]

,RED,GREEN,BLUE
0,0,0,0
1,0,0,128
2,0,0,139
3,0,0,205
4,0,0,238
...,...,...,...
1340,95,158,160
1341,96,123,139
1342,97,97,97
1343,99,184,255


In [18]:
all_data.iloc[:,0:3].min()

RED      0
GREEN    0
BLUE     0
dtype: int64

In [19]:
all_inputs = (all_data.iloc[:,0:3].values /255.0)

In [20]:
all_outputs = all_data.iloc[:, -1].values

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(all_inputs, all_outputs, test_size=1/3)

In [23]:
X_train

array([[0.46666667, 0.53333333, 0.6       ],
       [0.        , 0.60392157, 0.80392157],
       [1.        , 0.75686275, 0.14509804],
       ...,
       [0.47058824, 0.47058824, 0.47058824],
       [0.        , 0.        , 0.54509804],
       [0.54901961, 0.54901961, 0.54901961]], shape=(896, 3))

In [24]:
w_hidden = np.random.rand(3,3)

In [25]:
w_hidden

array([[0.00476824, 0.84242965, 0.62101029],
       [0.66525227, 0.7143401 , 0.52427297],
       [0.32508   , 0.21335506, 0.84971133]])

In [54]:
w_output = np.random.rand(1,3)

In [55]:
w_output

array([[0.69210953, 0.29049411, 0.58247567]])

In [56]:
b_hidden = np.random.rand(3,1)
b_output = np.random.rand(1,1)

In [57]:
relu = lambda x : np.maximum(x, 0)
logistic = lambda x : 1/(1+np.exp(-x))

In [58]:
def forward_prop(x):
    Z1 = w_hidden @ x + b_hidden
    A1 = relu(Z1)
    Z2 = w_output @ A1 + b_output
    A2 = logistic(Z2)
    return Z1, A1, Z2, A2

In [66]:
train_predictions = forward_prop(X_train.transpose())[3]

In [67]:
train_comparisons = np.equal((train_predictions >= 0.5).flatten().astype(int), Y_train)

In [68]:
accuracy = sum(train_comparisons.astype(int) / X_train.shape[0])

In [69]:
accuracy

np.float64(0.3906250000000024)