In [5]:
from numpy import array

i_hat1 = array([0,1])
j_hat1 = array([-1,0])
transform1 = array([i_hat1, j_hat1])
print(i_hat1)
print(j_hat1)
print(transform1)

[0 1]
[-1  0]
[[ 0  1]
 [-1  0]]


In [6]:
from numpy import array

i_hat1 = array([0,1])
j_hat1 = array([-1,0])
transform1 = array([i_hat1, j_hat1]).transpose()
print(i_hat1)
print(j_hat1)
print(transform1)

[0 1]
[-1  0]
[[ 0 -1]
 [ 1  0]]


In [7]:
i_hat2 = array([1,0])
j_hat2 = array([1,1])
transform2 = array([i_hat2, j_hat2]).transpose()

print(transform2)

[[1 1]
 [0 1]]


In [9]:
combined = transform1 @ transform2
print(combined)

[[ 0 -1]
 [ 1  1]]


In [ ]:
[[ 0 -1] [[1 1]
 [ 1  0]] [0 1]]

In [12]:
from numpy.linalg import det
from numpy import array
i_hat = array([3,0])
j_hat = array([0,2])

basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant)

6.0


In [15]:
from sympy import*

A = Matrix([
    [4,2,4],
    [5,3,7],
    [9,2,6]
])

inverse = A.inv()
identity = inverse * A
print("역행렬: {}".format(inverse))
print("항등 행렬: {}".format(identity))

역행렬: Matrix([[2/7, -2/7, 1/7], [33/14, -6/7, -4/7], [-17/14, 5/7, 1/7]])
항등 행렬: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [16]:
from numpy import array, diag
from numpy. linalg import eig, inv

A = array([
    [1,2],
    [4,5]
])

eigenvals, eigenvecs = eig(A)

print('고윳값')
print(eigenvals)
print('\n고유 벡터')
print(eigenvecs)

고윳값
[-0.46410162  6.46410162]

고유 벡터
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]
