In [2]:
import numpy as np

# ==============================
# 1. step 활성화 함수 정의
# ==============================
# step 함수는 퍼셉트론의 최종 출력값을 0 또는 1로 바꿔주는 함수입니다.
# z가 threshold 이상이면 1을 출력하고,
# z가 threshold보다 작으면 0을 출력합니다.
def step_function(z, threshold):
    if z >= threshold:
        return 1
    else:
        return 0


# ==============================
# 2. 입력 개수 n 받기
# ==============================
# 퍼셉트론에 들어갈 입력값의 개수를 사용자가 직접 정합니다.
# 예를 들어 n = 3이면 x1, x2, x3 총 3개의 입력값을 사용합니다.
n = int(input("입력 개수 n을 입력하세요: "))


# ==============================
# 3. 입력값 x 받기
# ==============================
# x는 사용자가 직접 입력합니다.
# 과제 조건에 따라 x 값은 0부터 1 사이의 값만 받습니다.
x_list = []

for i in range(n):
    while True:
        value = float(input(f"x{i+1} 값을 입력하세요(0~1): "))

        # 입력값이 0 이상 1 이하인지 검사합니다.
        if 0 <= value <= 1:
            x_list.append(value)
            break
        else:
            print("잘못된 입력입니다. 0부터 1 사이의 값을 입력하세요.")

# 입력받은 리스트를 numpy 배열로 바꿉니다.
# numpy 배열로 바꾸면 벡터 계산을 쉽게 할 수 있습니다.
x = np.array(x_list)


# ==============================
# 4. 가중치 w 랜덤 생성
# ==============================
# w는 입력값 x 각각에 곱해지는 중요도입니다.
# 과제 조건에 따라 w도 0부터 1 사이의 랜덤값으로 생성합니다.
# np.random.rand(n)은 0~1 사이의 랜덤값을 n개 만듭니다.
w = np.random.rand(n)


# ==============================
# 5. 가중합 z 계산
# ==============================
# 퍼셉트론은 입력값 x와 가중치 w를 각각 곱한 뒤 모두 더합니다.
#
# 예:
# x = [0.5, 0.8, 0.2]
# w = [0.3, 0.7, 0.4]
#
# z = 0.5*0.3 + 0.8*0.7 + 0.2*0.4
#
# np.dot(x, w)는 위 계산을 자동으로 해줍니다.
z = np.dot(x, w)


# ==============================
# 6. threshold 설정
# ==============================
# threshold는 0을 출력할지 1을 출력할지 결정하는 기준값입니다.
#
# z >= threshold 이면 출력 1
# z < threshold 이면 출력 0
#
# 여기서는 threshold를 "가능한 최대 점수의 절반"으로 설정했습니다.
# x가 모두 1일 때 가능한 최대 z값은 sum(w)입니다.
# 따라서 threshold = sum(w) * 0.5 로 두면,
# 전체 가능 점수의 절반 이상이면 1을 출력하게 됩니다.
threshold = np.sum(w) * 0.5


# ==============================
# 7. step 함수로 최종 출력 계산
# ==============================
# 가중합 z를 step 함수에 넣어서 최종 출력값 0 또는 1을 구합니다.
output = step_function(z, threshold)


# ==============================
# 8. 결과 출력
# ==============================
print("\n===== 퍼셉트론 계산 결과 =====")

print("입력값 x:")
print(x)

print("\n랜덤 가중치 w:")
print(w)

print("\n각 입력값과 가중치의 곱 x*w:")
print(x * w)

print("\n가중합 z = x1*w1 + x2*w2 + ... + xn*wn")
print(z)

print("\nthreshold 기준값:")
print(threshold)

print("\n최종 출력값:")
print(output)

입력 개수 n을 입력하세요:  3
x1 값을 입력하세요(0~1):  0.1
x2 값을 입력하세요(0~1):  0.4
x3 값을 입력하세요(0~1):  0.7



===== 퍼셉트론 계산 결과 =====
입력값 x:
[0.1 0.4 0.7]

랜덤 가중치 w:
[0.34489809 0.16916178 0.86273736]

각 입력값과 가중치의 곱 x*w:
[0.03448981 0.06766471 0.60391615]

가중합 z = x1*w1 + x2*w2 + ... + xn*wn
0.7060706778686408

threshold 기준값:
0.688398621440167

최종 출력값:
1
