In [2]:
#단일 퍼셉트론

import numpy as np

# ==============================
# 1. step 활성화 함수 정의
# ==============================
# step 함수는 퍼셉트론의 최종 출력값을 0 또는 1로 바꿔주는 함수입니다.
# z가 threshold 이상이면 1을 출력하고,
# z가 threshold보다 작으면 0을 출력합니다.
def step_function(z, threshold):
    if z >= threshold:
        return 1
    else:
        return 0


# ==============================
# 2. 입력 개수 n 받기
# ==============================
# 퍼셉트론에 들어갈 입력값의 개수를 사용자가 직접 정합니다.
# 예를 들어 n = 3이면 x1, x2, x3 총 3개의 입력값을 사용합니다.
n = int(input("입력 개수 n을 입력하세요: "))


# ==============================
# 3. 입력값 x 받기
# ==============================
# x는 사용자가 직접 입력합니다.
# 과제 조건에 따라 x 값은 0부터 1 사이의 값만 받습니다.
x_list = []

for i in range(n):
    while True:
        value = float(input(f"x{i+1} 값을 입력하세요(0~1): "))

        # 입력값이 0 이상 1 이하인지 검사합니다.
        if 0 <= value <= 1:
            x_list.append(value)
            break
        else:
            print("잘못된 입력입니다. 0부터 1 사이의 값을 입력하세요.")

# 입력받은 리스트를 numpy 배열로 바꿉니다.
# numpy 배열로 바꾸면 벡터 계산을 쉽게 할 수 있습니다.
x = np.array(x_list)


# ==============================
# 4. 가중치 w 랜덤 생성
# ==============================
# w는 입력값 x 각각에 곱해지는 중요도입니다.
# 과제 조건에 따라 w도 0부터 1 사이의 랜덤값으로 생성합니다.
# np.random.rand(n)은 0~1 사이의 랜덤값을 n개 만듭니다.
w = np.random.rand(n)


# ==============================
# 5. 가중합 z 계산
# ==============================
# 퍼셉트론은 입력값 x와 가중치 w를 각각 곱한 뒤 모두 더합니다.
#
# 예:
# x = [0.5, 0.8, 0.2]
# w = [0.3, 0.7, 0.4]
#
# z = 0.5*0.3 + 0.8*0.7 + 0.2*0.4
#
# np.dot(x, w)는 위 계산을 자동으로 해줍니다.
z = np.dot(x, w)


# ==============================
# 6. threshold 설정
# ==============================
# threshold는 0을 출력할지 1을 출력할지 결정하는 기준값입니다.
#
# z >= threshold 이면 출력 1
# z < threshold 이면 출력 0
#
# 여기서는 threshold를 "가능한 최대 점수의 절반"으로 설정했습니다.
# x가 모두 1일 때 가능한 최대 z값은 sum(w)입니다.
# 따라서 threshold = sum(w) * 0.5 로 두면,
# 전체 가능 점수의 절반 이상이면 1을 출력하게 됩니다.
threshold = np.sum(w) * 0.5


# ==============================
# 7. step 함수로 최종 출력 계산
# ==============================
# 가중합 z를 step 함수에 넣어서 최종 출력값 0 또는 1을 구합니다.
output = step_function(z, threshold)


# ==============================
# 8. 결과 출력
# ==============================
print("\n===== 퍼셉트론 계산 결과 =====")

print("입력값 x:")
print(x)

print("\n랜덤 가중치 w:")
print(w)

print("\n각 입력값과 가중치의 곱 x*w:")
print(x * w)

print("\n가중합 z = x1*w1 + x2*w2 + ... + xn*wn")
print(z)

print("\nthreshold 기준값:")
print(threshold)

print("\n최종 출력값:")
print(output)

입력 개수 n을 입력하세요:  3
x1 값을 입력하세요(0~1):  0.1
x2 값을 입력하세요(0~1):  0.4
x3 값을 입력하세요(0~1):  0.7



===== 퍼셉트론 계산 결과 =====
입력값 x:
[0.1 0.4 0.7]

랜덤 가중치 w:
[0.34489809 0.16916178 0.86273736]

각 입력값과 가중치의 곱 x*w:
[0.03448981 0.06766471 0.60391615]

가중합 z = x1*w1 + x2*w2 + ... + xn*wn
0.7060706778686408

threshold 기준값:
0.688398621440167

최종 출력값:
1


In [5]:
#정답을 보고 가중치와 threshold를 수정하는 학습형 단일 퍼셉트론

import numpy as np

# ==============================
# 1. step 활성화 함수 정의
# ==============================
# step 함수는 퍼셉트론의 최종 출력값을 0 또는 1로 바꿔주는 함수입니다.
# z가 threshold 이상이면 1을 출력하고,
# z가 threshold보다 작으면 0을 출력합니다.
def step_function(z, threshold):
    if z >= threshold:
        return 1
    else:
        return 0


# ==============================
# 2. 퍼셉트론 예측 함수 정의
# ==============================
# 입력값 x와 가중치 w를 곱해서 모두 더한 값이 z입니다.
# z = x1*w1 + x2*w2 + ... + xn*wn
#
# 그 다음 z를 threshold와 비교해서 0 또는 1을 출력합니다.
def predict(x, w, threshold):
    z = np.dot(x, w)
    output = step_function(z, threshold)
    return output, z


# ==============================
# 3. 입력 개수 n 받기
# ==============================
# 하나의 데이터가 몇 개의 입력값을 가지는지 정합니다.
# 예를 들어 n = 3이면 하나의 데이터는 [x1, x2, x3] 형태입니다.
n = int(input("입력 개수 n을 입력하세요: "))


# ==============================
# 4. 학습 데이터 개수 받기
# ==============================
# 퍼셉트론이 학습할 데이터의 개수를 정합니다.
# 예를 들어 AND 게이트라면 데이터가 4개입니다.
# [0,0] -> 0
# [0,1] -> 0
# [1,0] -> 0
# [1,1] -> 1
data_count = int(input("학습 데이터 개수를 입력하세요: "))


# ==============================
# 5. 학습 데이터 x와 정답 y 입력받기
# ==============================
# X에는 입력값들이 저장됩니다.
# y에는 각 입력값에 대한 정답이 저장됩니다.
X_list = []
y_list = []

for data_index in range(data_count):
    print(f"\n[{data_index + 1}번째 학습 데이터 입력]")

    x_values = []

    for i in range(n):
        while True:
            value = float(input(f"x{i+1} 값을 입력하세요(0~1): "))

            # 과제 조건에 따라 x는 0부터 1 사이만 허용합니다.
            if 0 <= value <= 1:
                x_values.append(value)
                break
            else:
                print("잘못된 입력입니다. 0부터 1 사이의 값을 입력하세요.")

    while True:
        target = int(input("정답 y를 입력하세요(0 또는 1): "))

        # 퍼셉트론의 정답은 0 또는 1만 사용합니다.
        if target == 0 or target == 1:
            break
        else:
            print("잘못된 입력입니다. 정답은 0 또는 1만 입력하세요.")

    X_list.append(x_values)
    y_list.append(target)


# 입력받은 학습 데이터를 numpy 배열로 변환합니다.
X = np.array(X_list)
y = np.array(y_list)


# ==============================
# 6. 가중치 w 랜덤 생성
# ==============================
# w는 입력값 각각에 곱해지는 중요도입니다.
# 과제 조건에 따라 0부터 1 사이의 랜덤값으로 초기화합니다.
w = np.random.rand(n)


# ==============================
# 7. threshold 초기값 설정
# ==============================
# threshold는 0과 1을 나누는 기준값입니다.
#
# z >= threshold 이면 1
# z < threshold 이면 0
#
# 처음에는 가능한 최대 점수의 절반 정도로 설정합니다.
# x가 모두 1일 때 z의 최대값은 sum(w)이므로,
# threshold를 sum(w) * 0.5로 둡니다.
threshold = np.sum(w) * 0.5


# ==============================
# 8. 학습률과 반복 횟수 설정
# ==============================
# learning_rate는 가중치를 얼마나 크게 수정할지 정하는 값입니다.
# 값이 너무 크면 학습이 불안정할 수 있고,
# 값이 너무 작으면 학습이 느릴 수 있습니다.
learning_rate = 0.1

# epochs는 전체 학습 데이터를 몇 번 반복해서 학습할지 정합니다.
epochs = 20


# ==============================
# 9. 학습 시작
# ==============================
print("\n===== 학습 시작 =====")

for epoch in range(epochs):
    total_error = 0

    print(f"\n[Epoch {epoch + 1}]")

    # 모든 학습 데이터를 하나씩 꺼내서 학습합니다.
    for i in range(data_count):
        x_i = X[i]
        target = y[i]

        # 현재 가중치와 threshold로 예측합니다.
        output, z = predict(x_i, w, threshold)

        # 오차 계산
        # 정답이 1인데 예측이 0이면 error = 1
        # 정답이 0인데 예측이 1이면 error = -1
        # 정답과 예측이 같으면 error = 0
        error = target - output

        # 오차의 절댓값을 누적합니다.
        # 한 epoch에서 틀린 횟수를 확인하기 위해 사용합니다.
        total_error += abs(error)

        # ==============================
        # 10. 가중치 학습 공식
        # ==============================
        # 퍼셉트론은 틀렸을 때 가중치를 수정합니다.
        #
        # w = w + learning_rate * error * x
        #
        # 정답이 1인데 예측이 0이면:
        # error = 1 이므로 w가 증가합니다.
        #
        # 정답이 0인데 예측이 1이면:
        # error = -1 이므로 w가 감소합니다.
        #
        # 정답과 예측이 같으면:
        # error = 0 이므로 w가 변하지 않습니다.
        w = w + learning_rate * error * x_i

        # ==============================
        # 11. threshold 수정
        # ==============================
        # threshold도 학습 과정에서 조금씩 조정합니다.
        #
        # output이 너무 작게 나오면 threshold를 낮춰서 1이 나오기 쉽게 만들고,
        # output이 너무 크게 나오면 threshold를 높여서 0이 나오기 쉽게 만듭니다.
        threshold = threshold - learning_rate * error

        print("입력:", x_i)
        print("정답:", target, "예측:", output, "오차:", error)
        print("가중합 z:", z)
        print("현재 w:", w)
        print("현재 threshold:", threshold)
        print()

    print("이번 epoch의 총 오차:", total_error)

    # 모든 데이터를 맞히면 더 이상 학습할 필요가 없으므로 종료합니다.
    if total_error == 0:
        print("\n모든 데이터를 맞혔으므로 학습을 조기 종료합니다.")
        break


# ==============================
# 12. 최종 학습 결과 출력
# ==============================
print("\n===== 최종 학습 결과 =====")
print("최종 가중치 w:")
print(w)

print("\n최종 threshold:")
print(threshold)


# ==============================
# 13. 학습된 퍼셉트론으로 최종 테스트
# ==============================
print("\n===== 최종 예측 결과 =====")

for i in range(data_count):
    x_i = X[i]
    target = y[i]
    output, z = predict(x_i, w, threshold)

    print("입력:", x_i)
    print("정답:", target)
    print("예측:", output)
    print("가중합 z:", z)
    print()

입력 개수 n을 입력하세요:  3
학습 데이터 개수를 입력하세요:  3



[1번째 학습 데이터 입력]


x1 값을 입력하세요(0~1):  0.1
x2 값을 입력하세요(0~1):  0.2
x3 값을 입력하세요(0~1):  0.5
정답 y를 입력하세요(0 또는 1):  1



[2번째 학습 데이터 입력]


x1 값을 입력하세요(0~1):  0.2
x2 값을 입력하세요(0~1):  0.3
x3 값을 입력하세요(0~1):  0.6
정답 y를 입력하세요(0 또는 1):  1



[3번째 학습 데이터 입력]


x1 값을 입력하세요(0~1):  0.2
x2 값을 입력하세요(0~1):  0.1
x3 값을 입력하세요(0~1):  0.1
정답 y를 입력하세요(0 또는 1):  0



===== 학습 시작 =====

[Epoch 1]
입력: [0.1 0.2 0.5]
정답: 1 예측: 0 오차: 1
가중합 z: 0.29950957629812935
현재 w: [0.05784271 0.41806933 0.48022288]
현재 threshold: 0.33806745897458623

입력: [0.2 0.3 0.6]
정답: 1 예측: 1 오차: 0
가중합 z: 0.42512306809304656
현재 w: [0.05784271 0.41806933 0.48022288]
현재 threshold: 0.33806745897458623

입력: [0.2 0.1 0.1]
정답: 0 예측: 0 오차: 0
가중합 z: 0.1013977625001575
현재 w: [0.05784271 0.41806933 0.48022288]
현재 threshold: 0.33806745897458623

이번 epoch의 총 오차: 1

[Epoch 2]
입력: [0.1 0.2 0.5]
정답: 1 예측: 0 오차: 1
가중합 z: 0.3295095762981293
현재 w: [0.06784271 0.43806933 0.53022288]
현재 threshold: 0.23806745897458623

입력: [0.2 0.3 0.6]
정답: 1 예측: 1 오차: 0
가중합 z: 0.4631230680930466
현재 w: [0.06784271 0.43806933 0.53022288]
현재 threshold: 0.23806745897458623

입력: [0.2 0.1 0.1]
정답: 0 예측: 0 오차: 0
가중합 z: 0.1103977625001575
현재 w: [0.06784271 0.43806933 0.53022288]
현재 threshold: 0.23806745897458623

이번 epoch의 총 오차: 1

[Epoch 3]
입력: [0.1 0.2 0.5]
정답: 1 예측: 1 오차: 0
가중합 z: 0.3595095762981293
현재 w: [0.06784271 0.